### ISSUE TITLE
The level of randomess

### ISSUE THREAD

**Issue by HassanGulzar** [SecretDeveloper/TestDataGenerator.Core#2]
If you loop a pattern a 1000 times, you'll get no more than 16 unique values. I have been using a RandomHelper class and I made a minor modification in you project and achieved 100% unique records.

Here is the change I made:

In GenerationConfig: Look at the commented code.

![image](https://cloud.githubusercontent.com/assets/825078/8519453/e49be470-23e3-11e5-9395-64dbc1e3f859.png)

The class I mentioned:
![image](https://cloud.githubusercontent.com/assets/825078/8519476/06e622de-23e4-11e5-8287-0f48b0ca28c4.png)

Are you aware of the default behaviour of the Random class? Did you allowed the repeat-possibility on purpose? I'm asking because there is a chance I might not have fully understood the mechanics of you library.

Thanks.

**Comment by HassanGulzar** [comment]
Does fail these tests though:

Can_Configure_And_Produce_Output_With_Seed
Can_Configure_And_Produce_Output_With_Seed2
GeneratePattern_Overloads2

**Comment by SecretDeveloper** [comment]
Hi,

The library does allow you to introduce a Seed value which is used to initialize the Random object.  This allows you to produce the same output which can be useful in certain circumstances.  Typically you do that by inserting a config section at the top of the input template:
```xml
<# { 'Seed':100 } #><<\.\w\W\L\l\V\v\d\D\S\s>>
```
or by explicitly supplying it in the GenerationConfig object:
```c#
string text = AlphaNumericGenerator.GenerateFromTemplate(@"<<\.\w\W\L\l\V\v\d\D\S\s>>", new GenerationConfig() { Seed = 100 });
```
So deterministic output is a feature, However when you say that you are only getting 16 values back when looping over 1000 values then that doesn't sound right.

I ran a quick test using the following:
```c#
        [TestMethod]
        [TestCategory("Randomness")]
        public void Level_Of_Randomness()
        {
            var pattern = @"(\L\L\L\L\L\L-\L\L-\L\L\L\L\L\n){1000}";
            var text = AlphaNumericGenerator.GenerateFromPattern(pattern, new GenerationConfig(){Seed = 100});
            File.WriteAllText(@"c:\temp\random.txt", text);
            Console.WriteLine(@"'{0}' produced \n{1}", pattern, text);
        }
```
and the produced file had no duplicate values although I doubt this is a valid test for the scenario you were using.

Have you got a unit test that reproduces what you were seeing?  
Also if you want to create a PR with your RandomHelper.cs changes then I can take a look at including them.

Thanks,
Gary

**Comment by HassanGulzar** [comment]
Could it be that I was doing a loop instead? Like:

#region Randomness
		[TestMethod]
		[TestCategory("Randomness")]
		public void Level_Of_Randomness()
		{
			var pattern = @"(\L\L\L\L\L\L-\L\L-\L\L\L\L\L\n){1000}";
			var text = AlphaNumericGenerator.GenerateFromPattern(pattern, new GenerationConfig() { Seed = 100 });
			var segments = new List<string>(text.Split(new[] { "\n" }, StringSplitOptions.RemoveEmptyEntries));
			
			Console.WriteLine(@"'{0}' produced {1} values, out of which, {2} are unique and {3} are duplicates.", pattern, segments.Count, segments.Distinct().Count(), segments.Count - segments.Distinct().Count());
		}

		[TestMethod]
		[TestCategory("Randomness")]
		public void Level_Of_Loop()
		{
			var pattern = @"(\L\L\L\L\L\L-\L\L-\L\L\L\L\L)";
			var segments = new List<string>();

			for (var i = 0; i < 1000; i++)
			{
				segments.Add(AlphaNumericGenerator.GenerateFromPattern(pattern, new GenerationConfig() { Seed = 100 }));
			}

			Console.WriteLine(@"'{0}' produced {1} values, out of which, {2} are unique and {3} are duplicates.", pattern, segments.Count, segments.Distinct().Count(), segments.Count - segments.Distinct().Count());
		}
		#endregion

You'll see that the for loop produces only one unique value and 999 are duplicates. I didn't know that  the pattern can have a segment describing loops.

**Comment by SecretDeveloper** [comment]
Ah ok that explains it a bit more, what is happening is that when you create a new GenerationConfig object it initializes its internal Random property using DateTime.Now.Millisecond as the initial seed value.  So when you your code runs in a loop a large number of iterations get initiated with the same Millisecond value which then produces exactly the same output.   

If you create the GenerationConfig object outside the loop then you don't get any duplicates:
```c#
[TestMethod]
        [TestCategory("Randomness")]
        public void Level_Of_Loop()
        {
            var pattern = @"(\L\L\L\L\L\L-\L\L-\L\L\L\L\L)";
            var segments = new List<string>();

            var config = new GenerationConfig();

            for (var i = 0; i < 1000; i++)
            {
                segments.Add(AlphaNumericGenerator.GenerateFromPattern(pattern, config));
            }

            Console.WriteLine(@"'{0}' produced {1} values, out of which, {2} are unique and {3} are duplicates.", pattern, segments.Count, segments.Distinct().Count(), segments.Count - segments.Distinct().Count());
        }

// Output -> 
// '(\L\L\L\L\L\L-\L\L-\L\L\L\L\L)' produced 1000 values, out of which, 1000 are unique and 0 are duplicates.
```

I can see how you would expect to be able to repeatedly call GenerateFromPattern in a loop and get back correct (random) results. I might need to rework that method to not behave counter intuitively.

**Comment by HassanGulzar** [comment]
That was it. I can work with the workaround provided. Thanks.
