### ISSUE TITLE
Dependency on "*.tgd-patterns" file

### ISSUE THREAD

**Issue by HassanGulzar** [SecretDeveloper/TestDataGenerator.Core#3]
Hello!

Is it possible to have no dependency or pre-requisite to have the default.tgd-patterns file existing?

**Comment by SecretDeveloper** [comment]
You should be able to delete the default.tdg-patterns file without encountering a problem as I only load the file if it is present.

**Comment by HassanGulzar** [comment]
In the abscence of the .tdg-patterns file, I'm getting FileIO exception

**Comment by SecretDeveloper** [comment]
Ok are you using the TDG command line application (https://github.com/SecretDeveloper/TDG) or just the core library as a reference in some other project?

**Comment by SecretDeveloper** [comment]
This should be resolved now with 4.0.2
