### ISSUE TITLE
StrongKey

### ISSUE THREAD

**Issue by HassanGulzar** [SecretDeveloper/TestDataGenerator.Core#5]
I'm not able to have my build server do a release mode build because the DLL from the NuGet is not strong key bound. Can you take care of this?

**Comment by SecretDeveloper** [comment]
I'll take a look in a few days.

**Comment by SecretDeveloper** [comment]
Strong signing the assembly seems to have some downsides and its not something i am looking to add to this project.  Can you tell me why you require it or why you are signing your own application? There are work arounds available although they take a little work.
